name: CI 

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: XCode Tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -parallel-testing-enabled YES -scheme ValidatableTextField-Package -enableCodeCoverage YES build test
    - name: Code Coverage
      run:
          bash <(curl -s https://codecov.io/bash) -J ValidatableTextField -t ${{secrets.CODECOV_TOKEN}}
  deploy_docs:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.JAZZY_TOKEN }}
        config: .jazzy.yml
